[package]
name = "pocket-tts-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pocket-tts-core = { path = "../pocket-tts-core" }
pocket-tts-model = { path = "../pocket-tts-model" }
axum = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
